// Auto-generated timezone data from IANA timezone database
// Total timezones: 417

export interface TimezoneInfo {
  value: string;
  label: string;
  region: string;
}

export const TIMEZONE_REGIONS = [
  'UTC',
  'Africa',
  'America', 
  'Antarctica',
  'Arctic',
  'Asia',
  'Atlantic',
  'Australia',
  'Europe',
  'Indian',
  'Pacific'
] as const;

export type TimezoneRegion = typeof TIMEZONE_REGIONS[number];

// Popular/commonly used timezones for quick access
export const POPULAR_TIMEZONES: TimezoneInfo[] = [
  { value: 'UTC', label: 'UTC (Coordinated Universal Time)', region: 'UTC' },
  { value: 'America/New_York', label: 'New York (Eastern Time)', region: 'America' },
  { value: 'America/Chicago', label: 'Chicago (Central Time)', region: 'America' },
  { value: 'America/Denver', label: 'Denver (Mountain Time)', region: 'America' },
  { value: 'America/Los_Angeles', label: 'Los Angeles (Pacific Time)', region: 'America' },
  { value: 'Europe/London', label: 'London (GMT/BST)', region: 'Europe' },
  { value: 'Europe/Paris', label: 'Paris (CET/CEST)', region: 'Europe' },
  { value: 'Europe/Berlin', label: 'Berlin (CET/CEST)', region: 'Europe' },
  { value: 'Asia/Tokyo', label: 'Tokyo (JST)', region: 'Asia' },
  { value: 'Asia/Shanghai', label: 'Shanghai (CST)', region: 'Asia' },
  { value: 'Asia/Kolkata', label: 'Kolkata (IST)', region: 'Asia' },
  { value: 'Australia/Sydney', label: 'Sydney (AEST/AEDT)', region: 'Australia' },
  { value: 'Pacific/Auckland', label: 'Auckland (NZST/NZDT)', region: 'Pacific' }
];

// All timezones grouped by region
export const TIMEZONES_BY_REGION: Record<TimezoneRegion, TimezoneInfo[]> = {
  UTC: [
    { value: 'UTC', label: 'UTC (Coordinated Universal Time)', region: 'UTC' }
  ],
  Africa: [
    { value: 'Africa/Abidjan', label: 'Abidjan', region: 'Africa' },
    { value: 'Africa/Accra', label: 'Accra', region: 'Africa' },
    { value: 'Africa/Addis_Ababa', label: 'Addis Ababa', region: 'Africa' },
    { value: 'Africa/Algiers', label: 'Algiers', region: 'Africa' },
    { value: 'Africa/Asmera', label: 'Asmera', region: 'Africa' },
    { value: 'Africa/Bamako', label: 'Bamako', region: 'Africa' },
    { value: 'Africa/Bangui', label: 'Bangui', region: 'Africa' },
    { value: 'Africa/Banjul', label: 'Banjul', region: 'Africa' },
    { value: 'Africa/Bissau', label: 'Bissau', region: 'Africa' },
    { value: 'Africa/Blantyre', label: 'Blantyre', region: 'Africa' },
    { value: 'Africa/Brazzaville', label: 'Brazzaville', region: 'Africa' },
    { value: 'Africa/Bujumbura', label: 'Bujumbura', region: 'Africa' },
    { value: 'Africa/Cairo', label: 'Cairo', region: 'Africa' },
    { value: 'Africa/Casablanca', label: 'Casablanca', region: 'Africa' },
    { value: 'Africa/Ceuta', label: 'Ceuta', region: 'Africa' },
    { value: 'Africa/Conakry', label: 'Conakry', region: 'Africa' },
    { value: 'Africa/Dakar', label: 'Dakar', region: 'Africa' },
    { value: 'Africa/Dar_es_Salaam', label: 'Dar es Salaam', region: 'Africa' },
    { value: 'Africa/Djibouti', label: 'Djibouti', region: 'Africa' },
    { value: 'Africa/Douala', label: 'Douala', region: 'Africa' },
    { value: 'Africa/El_Aaiun', label: 'El Aaiun', region: 'Africa' },
    { value: 'Africa/Freetown', label: 'Freetown', region: 'Africa' },
    { value: 'Africa/Gaborone', label: 'Gaborone', region: 'Africa' },
    { value: 'Africa/Harare', label: 'Harare', region: 'Africa' },
    { value: 'Africa/Johannesburg', label: 'Johannesburg', region: 'Africa' },
    { value: 'Africa/Juba', label: 'Juba', region: 'Africa' },
    { value: 'Africa/Kampala', label: 'Kampala', region: 'Africa' },
    { value: 'Africa/Khartoum', label: 'Khartoum', region: 'Africa' },
    { value: 'Africa/Kigali', label: 'Kigali', region: 'Africa' },
    { value: 'Africa/Kinshasa', label: 'Kinshasa', region: 'Africa' },
    { value: 'Africa/Lagos', label: 'Lagos', region: 'Africa' },
    { value: 'Africa/Libreville', label: 'Libreville', region: 'Africa' },
    { value: 'Africa/Lome', label: 'Lome', region: 'Africa' },
    { value: 'Africa/Luanda', label: 'Luanda', region: 'Africa' },
    { value: 'Africa/Lubumbashi', label: 'Lubumbashi', region: 'Africa' },
    { value: 'Africa/Lusaka', label: 'Lusaka', region: 'Africa' },
    { value: 'Africa/Malabo', label: 'Malabo', region: 'Africa' },
    { value: 'Africa/Maputo', label: 'Maputo', region: 'Africa' },
    { value: 'Africa/Maseru', label: 'Maseru', region: 'Africa' },
    { value: 'Africa/Mbabane', label: 'Mbabane', region: 'Africa' },
    { value: 'Africa/Mogadishu', label: 'Mogadishu', region: 'Africa' },
    { value: 'Africa/Monrovia', label: 'Monrovia', region: 'Africa' },
    { value: 'Africa/Nairobi', label: 'Nairobi', region: 'Africa' },
    { value: 'Africa/Ndjamena', label: 'Ndjamena', region: 'Africa' },
    { value: 'Africa/Niamey', label: 'Niamey', region: 'Africa' },
    { value: 'Africa/Nouakchott', label: 'Nouakchott', region: 'Africa' },
    { value: 'Africa/Ouagadougou', label: 'Ouagadougou', region: 'Africa' },
    { value: 'Africa/Porto-Novo', label: 'Porto-Novo', region: 'Africa' },
    { value: 'Africa/Sao_Tome', label: 'Sao Tome', region: 'Africa' },
    { value: 'Africa/Tripoli', label: 'Tripoli', region: 'Africa' },
    { value: 'Africa/Tunis', label: 'Tunis', region: 'Africa' },
    { value: 'Africa/Windhoek', label: 'Windhoek', region: 'Africa' },
  ],
  America: [
    { value: 'America/Adak', label: 'Adak', region: 'America' },
    { value: 'America/Anchorage', label: 'Anchorage', region: 'America' },
    { value: 'America/Anguilla', label: 'Anguilla', region: 'America' },
    { value: 'America/Antigua', label: 'Antigua', region: 'America' },
    { value: 'America/Araguaina', label: 'Araguaina', region: 'America' },
    { value: 'America/Argentina/La_Rioja', label: 'La Rioja', region: 'America' },
    { value: 'America/Argentina/Rio_Gallegos', label: 'Rio Gallegos', region: 'America' },
    { value: 'America/Argentina/Salta', label: 'Salta', region: 'America' },
    { value: 'America/Argentina/San_Juan', label: 'San Juan', region: 'America' },
    { value: 'America/Argentina/San_Luis', label: 'San Luis', region: 'America' },
    { value: 'America/Argentina/Tucuman', label: 'Tucuman', region: 'America' },
    { value: 'America/Argentina/Ushuaia', label: 'Ushuaia', region: 'America' },
    { value: 'America/Aruba', label: 'Aruba', region: 'America' },
    { value: 'America/Asuncion', label: 'Asuncion', region: 'America' },
    { value: 'America/Bahia', label: 'Bahia', region: 'America' },
    { value: 'America/Bahia_Banderas', label: 'Bahia Banderas', region: 'America' },
    { value: 'America/Barbados', label: 'Barbados', region: 'America' },
    { value: 'America/Belem', label: 'Belem', region: 'America' },
    { value: 'America/Belize', label: 'Belize', region: 'America' },
    { value: 'America/Blanc-Sablon', label: 'Blanc-Sablon', region: 'America' },
    { value: 'America/Boa_Vista', label: 'Boa Vista', region: 'America' },
    { value: 'America/Bogota', label: 'Bogota', region: 'America' },
    { value: 'America/Boise', label: 'Boise', region: 'America' },
    { value: 'America/Buenos_Aires', label: 'Buenos Aires', region: 'America' },
    { value: 'America/Cambridge_Bay', label: 'Cambridge Bay', region: 'America' },
    { value: 'America/Campo_Grande', label: 'Campo Grande', region: 'America' },
    { value: 'America/Cancun', label: 'Cancun', region: 'America' },
    { value: 'America/Caracas', label: 'Caracas', region: 'America' },
    { value: 'America/Catamarca', label: 'Catamarca', region: 'America' },
    { value: 'America/Cayenne', label: 'Cayenne', region: 'America' },
    { value: 'America/Cayman', label: 'Cayman', region: 'America' },
    { value: 'America/Chicago', label: 'Chicago (Central Time)', region: 'America' },
    { value: 'America/Chihuahua', label: 'Chihuahua', region: 'America' },
    { value: 'America/Ciudad_Juarez', label: 'Ciudad Juarez', region: 'America' },
    { value: 'America/Coral_Harbour', label: 'Coral Harbour', region: 'America' },
    { value: 'America/Cordoba', label: 'Cordoba', region: 'America' },
    { value: 'America/Costa_Rica', label: 'Costa Rica', region: 'America' },
    { value: 'America/Creston', label: 'Creston', region: 'America' },
    { value: 'America/Cuiaba', label: 'Cuiaba', region: 'America' },
    { value: 'America/Curacao', label: 'Curacao', region: 'America' },
    { value: 'America/Danmarkshavn', label: 'Danmarkshavn', region: 'America' },
    { value: 'America/Dawson', label: 'Dawson', region: 'America' },
    { value: 'America/Dawson_Creek', label: 'Dawson Creek', region: 'America' },
    { value: 'America/Denver', label: 'Denver (Mountain Time)', region: 'America' },
    { value: 'America/Detroit', label: 'Detroit', region: 'America' },
    { value: 'America/Dominica', label: 'Dominica', region: 'America' },
    { value: 'America/Edmonton', label: 'Edmonton', region: 'America' },
    { value: 'America/Eirunepe', label: 'Eirunepe', region: 'America' },
    { value: 'America/El_Salvador', label: 'El Salvador', region: 'America' },
    { value: 'America/Fort_Nelson', label: 'Fort Nelson', region: 'America' },
    { value: 'America/Fortaleza', label: 'Fortaleza', region: 'America' },
    { value: 'America/Glace_Bay', label: 'Glace Bay', region: 'America' },
    { value: 'America/Godthab', label: 'Godthab', region: 'America' },
    { value: 'America/Goose_Bay', label: 'Goose Bay', region: 'America' },
    { value: 'America/Grand_Turk', label: 'Grand Turk', region: 'America' },
    { value: 'America/Grenada', label: 'Grenada', region: 'America' },
    { value: 'America/Guadeloupe', label: 'Guadeloupe', region: 'America' },
    { value: 'America/Guatemala', label: 'Guatemala', region: 'America' },
    { value: 'America/Guayaquil', label: 'Guayaquil', region: 'America' },
    { value: 'America/Guyana', label: 'Guyana', region: 'America' },
    { value: 'America/Halifax', label: 'Halifax', region: 'America' },
    { value: 'America/Havana', label: 'Havana', region: 'America' },
    { value: 'America/Hermosillo', label: 'Hermosillo', region: 'America' },
    { value: 'America/Indiana/Knox', label: 'Knox', region: 'America' },
    { value: 'America/Indiana/Marengo', label: 'Marengo', region: 'America' },
    { value: 'America/Indiana/Petersburg', label: 'Petersburg', region: 'America' },
    { value: 'America/Indiana/Tell_City', label: 'Tell City', region: 'America' },
    { value: 'America/Indiana/Vevay', label: 'Vevay', region: 'America' },
    { value: 'America/Indiana/Vincennes', label: 'Vincennes', region: 'America' },
    { value: 'America/Indiana/Winamac', label: 'Winamac', region: 'America' },
    { value: 'America/Indianapolis', label: 'Indianapolis', region: 'America' },
    { value: 'America/Inuvik', label: 'Inuvik', region: 'America' },
    { value: 'America/Iqaluit', label: 'Iqaluit', region: 'America' },
    { value: 'America/Jamaica', label: 'Jamaica', region: 'America' },
    { value: 'America/Jujuy', label: 'Jujuy', region: 'America' },
    { value: 'America/Juneau', label: 'Juneau', region: 'America' },
    { value: 'America/Kentucky/Monticello', label: 'Monticello', region: 'America' },
    { value: 'America/Kralendijk', label: 'Kralendijk', region: 'America' },
    { value: 'America/La_Paz', label: 'La Paz', region: 'America' },
    { value: 'America/Lima', label: 'Lima', region: 'America' },
    { value: 'America/Los_Angeles', label: 'Los Angeles (Pacific Time)', region: 'America' },
    { value: 'America/Louisville', label: 'Louisville', region: 'America' },
    { value: 'America/Lower_Princes', label: 'Lower Princes', region: 'America' },
    { value: 'America/Maceio', label: 'Maceio', region: 'America' },
    { value: 'America/Managua', label: 'Managua', region: 'America' },
    { value: 'America/Manaus', label: 'Manaus', region: 'America' },
    { value: 'America/Marigot', label: 'Marigot', region: 'America' },
    { value: 'America/Martinique', label: 'Martinique', region: 'America' },
    { value: 'America/Matamoros', label: 'Matamoros', region: 'America' },
    { value: 'America/Mazatlan', label: 'Mazatlan', region: 'America' },
    { value: 'America/Mendoza', label: 'Mendoza', region: 'America' },
    { value: 'America/Menominee', label: 'Menominee', region: 'America' },
    { value: 'America/Merida', label: 'Merida', region: 'America' },
    { value: 'America/Metlakatla', label: 'Metlakatla', region: 'America' },
    { value: 'America/Mexico_City', label: 'Mexico City', region: 'America' },
    { value: 'America/Miquelon', label: 'Miquelon', region: 'America' },
    { value: 'America/Moncton', label: 'Moncton', region: 'America' },
    { value: 'America/Monterrey', label: 'Monterrey', region: 'America' },
    { value: 'America/Montevideo', label: 'Montevideo', region: 'America' },
    { value: 'America/Montserrat', label: 'Montserrat', region: 'America' },
    { value: 'America/Nassau', label: 'Nassau', region: 'America' },
    { value: 'America/New_York', label: 'New York (Eastern Time)', region: 'America' },
    { value: 'America/Nome', label: 'Nome', region: 'America' },
    { value: 'America/Noronha', label: 'Noronha', region: 'America' },
    { value: 'America/North_Dakota/Beulah', label: 'Beulah', region: 'America' },
    { value: 'America/North_Dakota/Center', label: 'Center', region: 'America' },
    { value: 'America/North_Dakota/New_Salem', label: 'New Salem', region: 'America' },
    { value: 'America/Ojinaga', label: 'Ojinaga', region: 'America' },
    { value: 'America/Panama', label: 'Panama', region: 'America' },
    { value: 'America/Paramaribo', label: 'Paramaribo', region: 'America' },
    { value: 'America/Phoenix', label: 'Phoenix', region: 'America' },
    { value: 'America/Port-au-Prince', label: 'Port-au-Prince', region: 'America' },
    { value: 'America/Port_of_Spain', label: 'Port of Spain', region: 'America' },
    { value: 'America/Porto_Velho', label: 'Porto Velho', region: 'America' },
    { value: 'America/Puerto_Rico', label: 'Puerto Rico', region: 'America' },
    { value: 'America/Punta_Arenas', label: 'Punta Arenas', region: 'America' },
    { value: 'America/Rankin_Inlet', label: 'Rankin Inlet', region: 'America' },
    { value: 'America/Recife', label: 'Recife', region: 'America' },
    { value: 'America/Regina', label: 'Regina', region: 'America' },
    { value: 'America/Resolute', label: 'Resolute', region: 'America' },
    { value: 'America/Rio_Branco', label: 'Rio Branco', region: 'America' },
    { value: 'America/Santarem', label: 'Santarem', region: 'America' },
    { value: 'America/Santiago', label: 'Santiago', region: 'America' },
    { value: 'America/Santo_Domingo', label: 'Santo Domingo', region: 'America' },
    { value: 'America/Sao_Paulo', label: 'Sao Paulo', region: 'America' },
    { value: 'America/Scoresbysund', label: 'Scoresbysund', region: 'America' },
    { value: 'America/Sitka', label: 'Sitka', region: 'America' },
    { value: 'America/St_Barthelemy', label: 'St Barthelemy', region: 'America' },
    { value: 'America/St_Johns', label: 'St Johns', region: 'America' },
    { value: 'America/St_Kitts', label: 'St Kitts', region: 'America' },
    { value: 'America/St_Lucia', label: 'St Lucia', region: 'America' },
    { value: 'America/St_Thomas', label: 'St Thomas', region: 'America' },
    { value: 'America/St_Vincent', label: 'St Vincent', region: 'America' },
    { value: 'America/Swift_Current', label: 'Swift Current', region: 'America' },
    { value: 'America/Tegucigalpa', label: 'Tegucigalpa', region: 'America' },
    { value: 'America/Thule', label: 'Thule', region: 'America' },
    { value: 'America/Tijuana', label: 'Tijuana', region: 'America' },
    { value: 'America/Toronto', label: 'Toronto', region: 'America' },
    { value: 'America/Tortola', label: 'Tortola', region: 'America' },
    { value: 'America/Vancouver', label: 'Vancouver', region: 'America' },
    { value: 'America/Whitehorse', label: 'Whitehorse', region: 'America' },
    { value: 'America/Winnipeg', label: 'Winnipeg', region: 'America' },
    { value: 'America/Yakutat', label: 'Yakutat', region: 'America' },
  ],
  Antarctica: [
    { value: 'Antarctica/Casey', label: 'Casey', region: 'Antarctica' },
    { value: 'Antarctica/Davis', label: 'Davis', region: 'Antarctica' },
    { value: 'Antarctica/DumontDUrville', label: 'DumontDUrville', region: 'Antarctica' },
    { value: 'Antarctica/Macquarie', label: 'Macquarie', region: 'Antarctica' },
    { value: 'Antarctica/Mawson', label: 'Mawson', region: 'Antarctica' },
    { value: 'Antarctica/McMurdo', label: 'McMurdo', region: 'Antarctica' },
    { value: 'Antarctica/Palmer', label: 'Palmer', region: 'Antarctica' },
    { value: 'Antarctica/Rothera', label: 'Rothera', region: 'Antarctica' },
    { value: 'Antarctica/Syowa', label: 'Syowa', region: 'Antarctica' },
    { value: 'Antarctica/Troll', label: 'Troll', region: 'Antarctica' },
    { value: 'Antarctica/Vostok', label: 'Vostok', region: 'Antarctica' },
  ],
  Arctic: [
    { value: 'Arctic/Longyearbyen', label: 'Longyearbyen', region: 'Arctic' },
  ],
  Asia: [
    { value: 'Asia/Aden', label: 'Aden', region: 'Asia' },
    { value: 'Asia/Almaty', label: 'Almaty', region: 'Asia' },
    { value: 'Asia/Amman', label: 'Amman', region: 'Asia' },
    { value: 'Asia/Anadyr', label: 'Anadyr', region: 'Asia' },
    { value: 'Asia/Aqtau', label: 'Aqtau', region: 'Asia' },
    { value: 'Asia/Aqtobe', label: 'Aqtobe', region: 'Asia' },
    { value: 'Asia/Ashgabat', label: 'Ashgabat', region: 'Asia' },
    { value: 'Asia/Atyrau', label: 'Atyrau', region: 'Asia' },
    { value: 'Asia/Baghdad', label: 'Baghdad', region: 'Asia' },
    { value: 'Asia/Bahrain', label: 'Bahrain', region: 'Asia' },
    { value: 'Asia/Baku', label: 'Baku', region: 'Asia' },
    { value: 'Asia/Bangkok', label: 'Bangkok', region: 'Asia' },
    { value: 'Asia/Barnaul', label: 'Barnaul', region: 'Asia' },
    { value: 'Asia/Beirut', label: 'Beirut', region: 'Asia' },
    { value: 'Asia/Bishkek', label: 'Bishkek', region: 'Asia' },
    { value: 'Asia/Brunei', label: 'Brunei', region: 'Asia' },
    { value: 'Asia/Calcutta', label: 'Calcutta', region: 'Asia' },
    { value: 'Asia/Chita', label: 'Chita', region: 'Asia' },
    { value: 'Asia/Colombo', label: 'Colombo', region: 'Asia' },
    { value: 'Asia/Damascus', label: 'Damascus', region: 'Asia' },
    { value: 'Asia/Dhaka', label: 'Dhaka', region: 'Asia' },
    { value: 'Asia/Dili', label: 'Dili', region: 'Asia' },
    { value: 'Asia/Dubai', label: 'Dubai', region: 'Asia' },
    { value: 'Asia/Dushanbe', label: 'Dushanbe', region: 'Asia' },
    { value: 'Asia/Famagusta', label: 'Famagusta', region: 'Asia' },
    { value: 'Asia/Gaza', label: 'Gaza', region: 'Asia' },
    { value: 'Asia/Hebron', label: 'Hebron', region: 'Asia' },
    { value: 'Asia/Hong_Kong', label: 'Hong Kong', region: 'Asia' },
    { value: 'Asia/Hovd', label: 'Hovd', region: 'Asia' },
    { value: 'Asia/Irkutsk', label: 'Irkutsk', region: 'Asia' },
    { value: 'Asia/Jakarta', label: 'Jakarta', region: 'Asia' },
    { value: 'Asia/Jayapura', label: 'Jayapura', region: 'Asia' },
    { value: 'Asia/Jerusalem', label: 'Jerusalem', region: 'Asia' },
    { value: 'Asia/Kabul', label: 'Kabul', region: 'Asia' },
    { value: 'Asia/Kamchatka', label: 'Kamchatka', region: 'Asia' },
    { value: 'Asia/Karachi', label: 'Karachi', region: 'Asia' },
    { value: 'Asia/Katmandu', label: 'Katmandu', region: 'Asia' },
    { value: 'Asia/Khandyga', label: 'Khandyga', region: 'Asia' },
    { value: 'Asia/Krasnoyarsk', label: 'Krasnoyarsk', region: 'Asia' },
    { value: 'Asia/Kuala_Lumpur', label: 'Kuala Lumpur', region: 'Asia' },
    { value: 'Asia/Kuching', label: 'Kuching', region: 'Asia' },
    { value: 'Asia/Kuwait', label: 'Kuwait', region: 'Asia' },
    { value: 'Asia/Macau', label: 'Macau', region: 'Asia' },
    { value: 'Asia/Magadan', label: 'Magadan', region: 'Asia' },
    { value: 'Asia/Makassar', label: 'Makassar', region: 'Asia' },
    { value: 'Asia/Manila', label: 'Manila', region: 'Asia' },
    { value: 'Asia/Muscat', label: 'Muscat', region: 'Asia' },
    { value: 'Asia/Nicosia', label: 'Nicosia', region: 'Asia' },
    { value: 'Asia/Novokuznetsk', label: 'Novokuznetsk', region: 'Asia' },
    { value: 'Asia/Novosibirsk', label: 'Novosibirsk', region: 'Asia' },
    { value: 'Asia/Omsk', label: 'Omsk', region: 'Asia' },
    { value: 'Asia/Oral', label: 'Oral', region: 'Asia' },
    { value: 'Asia/Phnom_Penh', label: 'Phnom Penh', region: 'Asia' },
    { value: 'Asia/Pontianak', label: 'Pontianak', region: 'Asia' },
    { value: 'Asia/Pyongyang', label: 'Pyongyang', region: 'Asia' },
    { value: 'Asia/Qatar', label: 'Qatar', region: 'Asia' },
    { value: 'Asia/Qostanay', label: 'Qostanay', region: 'Asia' },
    { value: 'Asia/Qyzylorda', label: 'Qyzylorda', region: 'Asia' },
    { value: 'Asia/Rangoon', label: 'Rangoon', region: 'Asia' },
    { value: 'Asia/Riyadh', label: 'Riyadh', region: 'Asia' },
    { value: 'Asia/Saigon', label: 'Saigon', region: 'Asia' },
    { value: 'Asia/Sakhalin', label: 'Sakhalin', region: 'Asia' },
    { value: 'Asia/Samarkand', label: 'Samarkand', region: 'Asia' },
    { value: 'Asia/Seoul', label: 'Seoul', region: 'Asia' },
    { value: 'Asia/Shanghai', label: 'Shanghai (CST)', region: 'Asia' },
    { value: 'Asia/Singapore', label: 'Singapore', region: 'Asia' },
    { value: 'Asia/Srednekolymsk', label: 'Srednekolymsk', region: 'Asia' },
    { value: 'Asia/Taipei', label: 'Taipei', region: 'Asia' },
    { value: 'Asia/Tashkent', label: 'Tashkent', region: 'Asia' },
    { value: 'Asia/Tbilisi', label: 'Tbilisi', region: 'Asia' },
    { value: 'Asia/Tehran', label: 'Tehran', region: 'Asia' },
    { value: 'Asia/Thimphu', label: 'Thimphu', region: 'Asia' },
    { value: 'Asia/Tokyo', label: 'Tokyo (JST)', region: 'Asia' },
    { value: 'Asia/Tomsk', label: 'Tomsk', region: 'Asia' },
    { value: 'Asia/Ulaanbaatar', label: 'Ulaanbaatar', region: 'Asia' },
    { value: 'Asia/Urumqi', label: 'Urumqi', region: 'Asia' },
    { value: 'Asia/Ust-Nera', label: 'Ust-Nera', region: 'Asia' },
    { value: 'Asia/Vientiane', label: 'Vientiane', region: 'Asia' },
    { value: 'Asia/Vladivostok', label: 'Vladivostok', region: 'Asia' },
    { value: 'Asia/Yakutsk', label: 'Yakutsk', region: 'Asia' },
    { value: 'Asia/Yekaterinburg', label: 'Yekaterinburg', region: 'Asia' },
    { value: 'Asia/Yerevan', label: 'Yerevan', region: 'Asia' },
  ],
  Atlantic: [
    { value: 'Atlantic/Azores', label: 'Azores', region: 'Atlantic' },
    { value: 'Atlantic/Bermuda', label: 'Bermuda', region: 'Atlantic' },
    { value: 'Atlantic/Canary', label: 'Canary', region: 'Atlantic' },
    { value: 'Atlantic/Cape_Verde', label: 'Cape Verde', region: 'Atlantic' },
    { value: 'Atlantic/Faeroe', label: 'Faeroe', region: 'Atlantic' },
    { value: 'Atlantic/Madeira', label: 'Madeira', region: 'Atlantic' },
    { value: 'Atlantic/Reykjavik', label: 'Reykjavik', region: 'Atlantic' },
    { value: 'Atlantic/South_Georgia', label: 'South Georgia', region: 'Atlantic' },
    { value: 'Atlantic/St_Helena', label: 'St Helena', region: 'Atlantic' },
    { value: 'Atlantic/Stanley', label: 'Stanley', region: 'Atlantic' },
  ],
  Australia: [
    { value: 'Australia/Adelaide', label: 'Adelaide', region: 'Australia' },
    { value: 'Australia/Brisbane', label: 'Brisbane', region: 'Australia' },
    { value: 'Australia/Broken_Hill', label: 'Broken Hill', region: 'Australia' },
    { value: 'Australia/Darwin', label: 'Darwin', region: 'Australia' },
    { value: 'Australia/Eucla', label: 'Eucla', region: 'Australia' },
    { value: 'Australia/Hobart', label: 'Hobart', region: 'Australia' },
    { value: 'Australia/Lindeman', label: 'Lindeman', region: 'Australia' },
    { value: 'Australia/Lord_Howe', label: 'Lord Howe', region: 'Australia' },
    { value: 'Australia/Melbourne', label: 'Melbourne', region: 'Australia' },
    { value: 'Australia/Perth', label: 'Perth', region: 'Australia' },
    { value: 'Australia/Sydney', label: 'Sydney (AEST/AEDT)', region: 'Australia' },
  ],
  Europe: [
    { value: 'Europe/Amsterdam', label: 'Amsterdam', region: 'Europe' },
    { value: 'Europe/Andorra', label: 'Andorra', region: 'Europe' },
    { value: 'Europe/Astrakhan', label: 'Astrakhan', region: 'Europe' },
    { value: 'Europe/Athens', label: 'Athens', region: 'Europe' },
    { value: 'Europe/Belgrade', label: 'Belgrade', region: 'Europe' },
    { value: 'Europe/Berlin', label: 'Berlin (CET/CEST)', region: 'Europe' },
    { value: 'Europe/Bratislava', label: 'Bratislava', region: 'Europe' },
    { value: 'Europe/Brussels', label: 'Brussels', region: 'Europe' },
    { value: 'Europe/Bucharest', label: 'Bucharest', region: 'Europe' },
    { value: 'Europe/Budapest', label: 'Budapest', region: 'Europe' },
    { value: 'Europe/Busingen', label: 'Busingen', region: 'Europe' },
    { value: 'Europe/Chisinau', label: 'Chisinau', region: 'Europe' },
    { value: 'Europe/Copenhagen', label: 'Copenhagen', region: 'Europe' },
    { value: 'Europe/Dublin', label: 'Dublin', region: 'Europe' },
    { value: 'Europe/Gibraltar', label: 'Gibraltar', region: 'Europe' },
    { value: 'Europe/Guernsey', label: 'Guernsey', region: 'Europe' },
    { value: 'Europe/Helsinki', label: 'Helsinki', region: 'Europe' },
    { value: 'Europe/Isle_of_Man', label: 'Isle of Man', region: 'Europe' },
    { value: 'Europe/Istanbul', label: 'Istanbul', region: 'Europe' },
    { value: 'Europe/Jersey', label: 'Jersey', region: 'Europe' },
    { value: 'Europe/Kaliningrad', label: 'Kaliningrad', region: 'Europe' },
    { value: 'Europe/Kiev', label: 'Kiev', region: 'Europe' },
    { value: 'Europe/Kirov', label: 'Kirov', region: 'Europe' },
    { value: 'Europe/Lisbon', label: 'Lisbon', region: 'Europe' },
    { value: 'Europe/Ljubljana', label: 'Ljubljana', region: 'Europe' },
    { value: 'Europe/London', label: 'London (GMT/BST)', region: 'Europe' },
    { value: 'Europe/Luxembourg', label: 'Luxembourg', region: 'Europe' },
    { value: 'Europe/Madrid', label: 'Madrid', region: 'Europe' },
    { value: 'Europe/Malta', label: 'Malta', region: 'Europe' },
    { value: 'Europe/Mariehamn', label: 'Mariehamn', region: 'Europe' },
    { value: 'Europe/Minsk', label: 'Minsk', region: 'Europe' },
    { value: 'Europe/Monaco', label: 'Monaco', region: 'Europe' },
    { value: 'Europe/Moscow', label: 'Moscow', region: 'Europe' },
    { value: 'Europe/Oslo', label: 'Oslo', region: 'Europe' },
    { value: 'Europe/Paris', label: 'Paris (CET/CEST)', region: 'Europe' },
    { value: 'Europe/Podgorica', label: 'Podgorica', region: 'Europe' },
    { value: 'Europe/Prague', label: 'Prague', region: 'Europe' },
    { value: 'Europe/Riga', label: 'Riga', region: 'Europe' },
    { value: 'Europe/Rome', label: 'Rome', region: 'Europe' },
    { value: 'Europe/Samara', label: 'Samara', region: 'Europe' },
    { value: 'Europe/San_Marino', label: 'San Marino', region: 'Europe' },
    { value: 'Europe/Sarajevo', label: 'Sarajevo', region: 'Europe' },
    { value: 'Europe/Saratov', label: 'Saratov', region: 'Europe' },
    { value: 'Europe/Simferopol', label: 'Simferopol', region: 'Europe' },
    { value: 'Europe/Skopje', label: 'Skopje', region: 'Europe' },
    { value: 'Europe/Sofia', label: 'Sofia', region: 'Europe' },
    { value: 'Europe/Stockholm', label: 'Stockholm', region: 'Europe' },
    { value: 'Europe/Tallinn', label: 'Tallinn', region: 'Europe' },
    { value: 'Europe/Tirane', label: 'Tirane', region: 'Europe' },
    { value: 'Europe/Ulyanovsk', label: 'Ulyanovsk', region: 'Europe' },
    { value: 'Europe/Vaduz', label: 'Vaduz', region: 'Europe' },
    { value: 'Europe/Vatican', label: 'Vatican', region: 'Europe' },
    { value: 'Europe/Vienna', label: 'Vienna', region: 'Europe' },
    { value: 'Europe/Vilnius', label: 'Vilnius', region: 'Europe' },
    { value: 'Europe/Volgograd', label: 'Volgograd', region: 'Europe' },
    { value: 'Europe/Warsaw', label: 'Warsaw', region: 'Europe' },
    { value: 'Europe/Zagreb', label: 'Zagreb', region: 'Europe' },
    { value: 'Europe/Zurich', label: 'Zurich', region: 'Europe' },
  ],
  Indian: [
    { value: 'Indian/Antananarivo', label: 'Antananarivo', region: 'Indian' },
    { value: 'Indian/Chagos', label: 'Chagos', region: 'Indian' },
    { value: 'Indian/Christmas', label: 'Christmas', region: 'Indian' },
    { value: 'Indian/Cocos', label: 'Cocos', region: 'Indian' },
    { value: 'Indian/Comoro', label: 'Comoro', region: 'Indian' },
    { value: 'Indian/Kerguelen', label: 'Kerguelen', region: 'Indian' },
    { value: 'Indian/Mahe', label: 'Mahe', region: 'Indian' },
    { value: 'Indian/Maldives', label: 'Maldives', region: 'Indian' },
    { value: 'Indian/Mauritius', label: 'Mauritius', region: 'Indian' },
    { value: 'Indian/Mayotte', label: 'Mayotte', region: 'Indian' },
    { value: 'Indian/Reunion', label: 'Reunion', region: 'Indian' },
  ],
  Pacific: [
    { value: 'Pacific/Apia', label: 'Apia', region: 'Pacific' },
    { value: 'Pacific/Auckland', label: 'Auckland (NZST/NZDT)', region: 'Pacific' },
    { value: 'Pacific/Bougainville', label: 'Bougainville', region: 'Pacific' },
    { value: 'Pacific/Chatham', label: 'Chatham', region: 'Pacific' },
    { value: 'Pacific/Easter', label: 'Easter', region: 'Pacific' },
    { value: 'Pacific/Efate', label: 'Efate', region: 'Pacific' },
    { value: 'Pacific/Enderbury', label: 'Enderbury', region: 'Pacific' },
    { value: 'Pacific/Fakaofo', label: 'Fakaofo', region: 'Pacific' },
    { value: 'Pacific/Fiji', label: 'Fiji', region: 'Pacific' },
    { value: 'Pacific/Funafuti', label: 'Funafuti', region: 'Pacific' },
    { value: 'Pacific/Galapagos', label: 'Galapagos', region: 'Pacific' },
    { value: 'Pacific/Gambier', label: 'Gambier', region: 'Pacific' },
    { value: 'Pacific/Guadalcanal', label: 'Guadalcanal', region: 'Pacific' },
    { value: 'Pacific/Guam', label: 'Guam', region: 'Pacific' },
    { value: 'Pacific/Honolulu', label: 'Honolulu', region: 'Pacific' },
    { value: 'Pacific/Kiritimati', label: 'Kiritimati', region: 'Pacific' },
    { value: 'Pacific/Kosrae', label: 'Kosrae', region: 'Pacific' },
    { value: 'Pacific/Kwajalein', label: 'Kwajalein', region: 'Pacific' },
    { value: 'Pacific/Majuro', label: 'Majuro', region: 'Pacific' },
    { value: 'Pacific/Marquesas', label: 'Marquesas', region: 'Pacific' },
    { value: 'Pacific/Midway', label: 'Midway', region: 'Pacific' },
    { value: 'Pacific/Nauru', label: 'Nauru', region: 'Pacific' },
    { value: 'Pacific/Niue', label: 'Niue', region: 'Pacific' },
    { value: 'Pacific/Norfolk', label: 'Norfolk', region: 'Pacific' },
    { value: 'Pacific/Noumea', label: 'Noumea', region: 'Pacific' },
    { value: 'Pacific/Pago_Pago', label: 'Pago Pago', region: 'Pacific' },
    { value: 'Pacific/Palau', label: 'Palau', region: 'Pacific' },
    { value: 'Pacific/Pitcairn', label: 'Pitcairn', region: 'Pacific' },
    { value: 'Pacific/Ponape', label: 'Ponape', region: 'Pacific' },
    { value: 'Pacific/Port_Moresby', label: 'Port Moresby', region: 'Pacific' },
    { value: 'Pacific/Rarotonga', label: 'Rarotonga', region: 'Pacific' },
    { value: 'Pacific/Saipan', label: 'Saipan', region: 'Pacific' },
    { value: 'Pacific/Tahiti', label: 'Tahiti', region: 'Pacific' },
    { value: 'Pacific/Tarawa', label: 'Tarawa', region: 'Pacific' },
    { value: 'Pacific/Tongatapu', label: 'Tongatapu', region: 'Pacific' },
    { value: 'Pacific/Truk', label: 'Truk', region: 'Pacific' },
    { value: 'Pacific/Wake', label: 'Wake', region: 'Pacific' },
    { value: 'Pacific/Wallis', label: 'Wallis', region: 'Pacific' },
  ],
};

// Flat array of all timezones
export const ALL_TIMEZONES: TimezoneInfo[] = [
  ...TIMEZONES_BY_REGION.UTC,
  ...TIMEZONES_BY_REGION.Africa,
  ...TIMEZONES_BY_REGION.America,
  ...TIMEZONES_BY_REGION.Antarctica,
  ...TIMEZONES_BY_REGION.Arctic,
  ...TIMEZONES_BY_REGION.Asia,
  ...TIMEZONES_BY_REGION.Atlantic,
  ...TIMEZONES_BY_REGION.Australia,
  ...TIMEZONES_BY_REGION.Europe,
  ...TIMEZONES_BY_REGION.Indian,
  ...TIMEZONES_BY_REGION.Pacific,
];

// Helper function to get timezone info by value
export const getTimezoneInfo = (value: string): TimezoneInfo | undefined => {
  return ALL_TIMEZONES.find(tz => tz.value === value);
};

// Helper function to search timezones
export const searchTimezones = (query: string): TimezoneInfo[] => {
  const lowercaseQuery = query.toLowerCase();
  return ALL_TIMEZONES.filter(tz => 
    tz.label.toLowerCase().includes(lowercaseQuery) ||
    tz.value.toLowerCase().includes(lowercaseQuery)
  );
};

